#!/bin/sh

# cleanup
rm -rf obj_dir
rm -f *.vcd

# run Verilator to translate Verilog into C++, including C++ testbench
verilator -Wall --cc --trace f1_lightseq.sv --exe f1_lightseq_tb.cpp

# build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Vf1_lightseq.mk Vf1_lightseq

# run executable simulation file
echo "\nRunning simulation"
obj_dir/Vf1_lightseq
echo "\nSimulation completed"

